apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "twinny-server.fullname" . }}-config
  labels:
    {{- include "twinny-server.labels" . | nindent 4 }}
data:
  twinny.gateway.json: |
    {{- toPrettyJson .Values.config | nindent 4 }}
