{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "twinny-server.fullname" . }}
  labels:
    {{- include "twinny-server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "twinny-server.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      authorization:
        credentials:
          name: {{ .Values.serviceMonitor.secretName }}
          key: token
{{- end }}
